### ISSUE TITLE
Console spam when failing to connect to IRC server.

### ISSUE THREAD

**Issue by Kattus** [CraftIRC/3#55]
Really annoying spam when the IRC server is unreachable.
![2013-12-19_23-05-07](https://f.cloud.github.com/assets/6226312/1786775/bc00cd64-68fa-11e3-92a5-66e117e7daec.png)

**Comment by mbax** [comment]
https://github.com/CraftIRC/3/commit/4799bfdea8a9f824dfeaf19110b938545bda31c4
