### ISSUE TITLE
Allow reply with NOTICE (aka whisper) instead of just in channel or pm

### ISSUE THREAD

**Issue by buglord** [CraftIRC/3#62]
I would have contributed myself but I am not familiar enough with the code to locate and modify all relevant sections.

I suggest deprecating (but not yet removing, for backwards compatibility reasons) the current config option and creating one to specify reply method (channel message, user message, user notice)

**Comment by mbax** [comment]
https://github.com/CraftIRC/3/commit/5a49c242d29b656ff1c69e24e207cbd824b1a8e4
